[package]
name = "aba-cache"
version = "0.1.0-SNAPSHOT"
authors = ["Arief Bastian HB <ariefbastian@gmail.com>"]
edition = "2018"

[dependencies]
slab = "0.4"
tokio = { version = "0.2", features = ["sync", "parking_lot"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["macros", "rt-core", "time"] }